# Generated by Django 4.2.24 on 2025-09-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rating_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books_author', to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(related_name='books_publisher', to='books.publisher'),
        ),
    ]
