# Generated by Django 4.2.24 on 2025-09-19 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_image_book_cover_alter_book_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='isbnmodel',
            old_name='pages',
            new_name='total_pages',
        ),
        migrations.AddField(
            model_name='book',
            name='primary_isbn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_books', to='books.isbnmodel'),
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('start_page', models.PositiveIntegerField(blank=True, null=True)),
                ('end_page', models.PositiveIntegerField(blank=True, null=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='books.bookprogress')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
