# Generated by Django 4.2.24 on 2025-09-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_delete_readingsession'),
        ('books', '0004_bookprogress_rename_pages_isbnmodel_total_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsession',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='shelves.bookprogress'),
        ),
        migrations.DeleteModel(
            name='BookProgress',
        ),
    ]
