# Generated by Django 4.2.24 on 2025-09-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rating_art_score_rating_atmosphere_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='language_score',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='logic_score',
        ),
    ]
