# Generated by Django 4.2.24 on 2025-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_rating_language_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition_group_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Служебный ключ для объединения изданий одной книги.', max_length=512),
        ),
    ]
