# Generated by Django 4.2.24 on 2025-10-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
