# Generated by Django 4.2.13 on 2025-11-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0017_shelf_is_managed'),
        ('books', '0014_alter_ratingcomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsession',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='shelves.bookprogress'),
        ),
    ]
