# Generated by Django 4.2.13 on 2025-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_readingsession_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
