# Generated by Django 4.2.13 on 2025-11-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_page_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page_count',
        ),
    ]
