# Generated by Django 4.2.13 on 2026-02-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_bookeditrequest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='isbnmodel',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_isbnmodel_id'),
        ),
    ]
