# Generated by Django 4.2.13 on 2026-06-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_book_book_title_idx_book_book_created_at_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Автоматически созданное превью обложки 160×240 WebP для списков.', null=True, upload_to='book_covers/thumbnails/'),
        ),
    ]
