# Generated by Django 4.2.13 on 2026-07-11 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0023_book_cover_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='hidden_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='is_hidden_by_admin',
            field=models.BooleanField(db_index=True, default=False, help_text='Скрыть книгу из публичного каталога, поиска и общих подборок.'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Владелец личной книги, если она не публикуется в общем каталоге.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='visibility',
            field=models.CharField(choices=[('public', 'В общем каталоге'), ('private', 'Личная книга')], db_index=True, default='public', help_text='Определяет, видна ли книга в общем каталоге или только владельцу.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['visibility', 'is_hidden_by_admin'], name='book_visibility_idx'),
        ),
    ]
