# Generated by Django 4.2.24 on 2025-10-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_clubs', '0002_discussionpost_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingclub',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
