# Generated by Django 4.2.13 on 2025-12-28 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reading_clubs', '0003_alter_readingclub_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionpost',
            options={'ordering': ('created_at', 'id')},
        ),
        migrations.CreateModel(
            name='DiscussionRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний просмотр')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='reading_clubs.readingnorm', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_discussion_reads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр обсуждения',
                'verbose_name_plural': 'Просмотры обсуждений',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
