# Generated by Django 4.2.24 on 2025-10-04 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_authoroffer_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorofferresponse',
            name='platform_links',
            field=models.TextField(blank=True, help_text='Укажите ссылки на площадки построчно.', verbose_name='Площадки для отзывов'),
        ),
        migrations.AlterField(
            model_name='authorofferresponse',
            name='message',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Сообщение'),
        ),
    ]
