# Generated by hand
from django.conf import settings
from django.core.validators import MaxLengthValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborations", "0003_authorofferresponse_platform_links_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorOfferResponseComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(validators=[MaxLengthValidator(1000)], verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="offer_response_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="comments",
                        to="collaborations.authorofferresponse",
                        verbose_name="Отклик",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "verbose_name": "Комментарий к отклику",
                "verbose_name_plural": "Комментарии к откликам",
            },
        ),
    ]