# Generated by Django 4.2.23 on 2025-10-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0007_bloggerrequest_target_audience_and_more'),
        ('collaborations', '0011_activity_tracking'),
    ]

    operations = [
    ]
