# Generated by Django 4.2.13 on 2025-10-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0013_bloggerrequest_blogger_collaboration_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggerrequestresponse',
            options={'ordering': ('-created_at',), 'verbose_name': 'Отклик на заявку блогера', 'verbose_name_plural': 'Отклики на заявки блогеров'},
        ),
    ]
