# Generated by Django 4.2.13 on 2025-11-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0015_remove_bloggerrequest_open_for_paid_collaboration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationmessage',
            name='epub_file',
            field=models.FileField(blank=True, help_text='Опциональное вложение с текстом книги.', null=True, upload_to='collaborations/epubs/%Y/%m/%d', verbose_name='EPUB-файл'),
        ),
    ]
