# Generated by Django 4.2.24 on 2025-10-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_premiumpayment_premiumsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='premiumsubscription',
            new_name='accounts_pr_user_id_5c1663_idx',
            old_name='accounts_premium_sub_user_end_idx',
        ),
    ]
