# Generated by Django 4.2.13 on 2025-11-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_coins_cointransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cointransaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_daily_reward_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ad_reward', 'Награда за просмотр рекламы'), ('daily_login', 'Бонус за ежедневный вход'), ('signup_bonus', 'Приветственный бонус'), ('admin_adjustment', 'Корректировка администратором'), ('feature_purchase', 'Трата на функцию')], max_length=40),
        ),
    ]
