# Generated by Django 4.2.13 on 2025-11-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cointransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='method',
            field=models.CharField(choices=[('yoomoney', 'ЮMoney кошелёк')], max_length=20),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='plan',
            field=models.CharField(choices=[('month', '1 месяц')], max_length=20),
        ),
    ]
