# Generated by Django 4.2.13 on 2025-11-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='confirmation_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='idempotence_key',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='method',
            field=models.CharField(choices=[('yoomoney', 'YooKassa')], max_length=20),
        ),
    ]
