# Generated by Django 4.2.13 on 2025-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_premiumpayment_confirmation_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpayment',
            name='plan',
            field=models.CharField(choices=[('month', '1 месяц'), ('subscription_300', 'Подписка 300 ₽')], max_length=20),
        ),
    ]
