# Generated by Django 4.2.13 on 2026-08-03 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bookchallenge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardAdTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('vk', 'VK Реклама'), ('yandex', 'Яндекс Реклама')], max_length=20)),
                ('ad_unit_id', models.CharField(blank=True, max_length=120)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('not_before', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_ad_tickets', to='accounts.profile')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_ad_ticket', to='accounts.cointransaction')),
            ],
            options={
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['profile', 'issued_at'], name='reward_ad_profile_issued_idx'), models.Index(fields=['profile', 'claimed_at'], name='reward_ad_profile_claimed_idx')],
            },
        ),
    ]
