# Generated by Django 4.2.24 on 2025-10-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userpointevent',
            new_name='user_rating_user_id_3ba47c_idx',
            old_name='user_events_idx',
        ),
        migrations.RenameIndex(
            model_name='userpointevent',
            new_name='user_rating_content_fbb89f_idx',
            old_name='user_events_object_idx',
        ),
    ]
