# Generated by Django 4.2.24 on 2025-09-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_edition_group_key'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameshelfpurchase',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_purchases', to='books.book'),
        ),
    ]
