# Generated by Django 4.2.24 on 2025-09-30 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameshelfpurchase_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameshelfstate',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
