# Generated by Django 4.2.13 on 2025-11-03 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0015_alter_readingsession_progress'),
        ('games', '0006_bookexchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgottenbookentry',
            options={'ordering': ['added_at']},
        ),
        migrations.AddField(
            model_name='forgottenbookentry',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forgottenbookentry',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forgottenbookentry',
            name='review_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forgottenbookentry',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forgottenbookentry',
            name='selected_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forgottenbookentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forgottenbookentry',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgotten_book_entries', to='books.book'),
        ),
        migrations.AlterField(
            model_name='forgottenbookentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgotten_book_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='forgottenbookentry',
            unique_together={('user', 'book')},
        ),
    ]
