# Generated by Django 4.2.13 on 2025-11-07 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_readingsession_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_alter_forgottenbookentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NobelLaureateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Выполнено')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nobel_assignments', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nobel_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('user', 'stage_number')},
            },
        ),
    ]
