# Generated by Django 4.2.13 on 2026-04-22 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_book_book_title_idx_book_book_created_at_idx_and_more'),
        ('games', '0008_nobellaureateassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='YasnayaPolyanaNominationBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shortlist', models.BooleanField(default=False, help_text='Книга входит в короткий список номинации.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yasnaya_polyana_nominations', to='books.book')),
            ],
            options={
                'ordering': ['-is_shortlist', 'book__title'],
                'unique_together': {('book',)},
            },
        ),
    ]
