# Generated by Django 4.2.13 on 2026-04-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_yasnayapolyananominationbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Год сезона/премии (для ежегодных игр).', null=True),
        ),
    ]
