# Generated by Django 4.2.13 on 2026-04-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_add_game_to_yasnaya_polyana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yasnayapolyananominationbook',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yasnaya_polyana_nominations', to='games.game'),
        ),
    ]
