# Generated by Django 4.2.13 on 2026-07-12 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0024_book_hidden_at_book_hidden_reason_and_more'),
        ('games', '0012_alter_yasnayapolyananominationbook_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mini-books', 'Mini books'), ('book-list', 'Book list'), ('pages-minutes', 'Pages and minutes')], db_index=True, max_length=32)),
                ('month', models.DateField(db_index=True)),
                ('target_books', models.PositiveIntegerField(blank=True, null=True)),
                ('target_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('target_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyChallengeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_challenge_books', to='books.book')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='games.monthlychallenge')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('challenge', 'book')},
            },
        ),
        migrations.AddIndex(
            model_name='monthlychallenge',
            index=models.Index(fields=['user', 'kind', 'month'], name='games_month_user_id_ea3475_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlychallenge',
            unique_together={('user', 'kind', 'month')},
        ),
    ]
