# Generated by Django 4.2.24 on 2025-09-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_event_eventparticipant_bookprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookprogress',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bookprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookprogress',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_progress', to='shelves.event'),
        ),
        migrations.AddConstraint(
            model_name='bookprogress',
            constraint=models.UniqueConstraint(fields=('event', 'user', 'book'), name='uniq_progress_per_event'),
        ),
        migrations.AddConstraint(
            model_name='bookprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', True)), fields=('user', 'book'), name='uniq_progress_no_event'),
        ),
    ]
