# Generated by Django 4.2.24 on 2025-09-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_readingsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingSession',
        ),
    ]
