# Generated by Django 4.2.24 on 2025-09-25 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_delete_readingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shelves.bookprogress')),
            ],
            options={
                'ordering': ['-log_date'],
                'unique_together': {('progress', 'log_date')},
            },
        ),
    ]
