# Generated by Django 4.2.24 on 2025-09-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0006_readinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprogress',
            name='character_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='reading_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
