# Generated by Django 4.2.24 on 2025-09-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0007_bookprogress_character_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprogress',
            name='character_notes',
        ),
        migrations.CreateModel(
            name='CharacterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_entries', to='shelves.bookprogress')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
