# Generated by Django 4.2.24 on 2025-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0008_remove_bookprogress_character_notes_characternote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprogress',
            name='audio_length',
            field=models.DurationField(blank=True, help_text='Полная длительность аудиокниги', null=True),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='audio_playback_speed',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Скорость прослушивания аудиокниги', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='custom_total_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Количество страниц, указанное пользователем, если нет данных об издании', null=True),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='format',
            field=models.CharField(choices=[('paper', 'Бумажная книга'), ('ebook', 'Электронная книга'), ('audiobook', 'Аудиокнига')], default='paper', help_text='Формат, в котором пользователь читает книгу', max_length=20),
        ),
    ]
