# Generated by Django 4.2.24 on 2025-09-30 15:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0009_bookprogress_audio_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(blank=True, help_text='Издание, тираж или дополнительная информация', max_length=200)),
                ('language', models.CharField(blank=True, help_text='Язык конкретного экземпляра', max_length=50)),
                ('format', models.CharField(choices=[('paper', 'Бумажная'), ('ebook', 'Электронная'), ('audio', 'Аудио'), ('other', 'Другое')], default='paper', max_length=20)),
                ('status', models.CharField(blank=True, help_text='Например: в коллекции, отдана другу, зарезервирована', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Где хранится книга: комната, шкаф, полка', max_length=100)),
                ('shelf_section', models.CharField(blank=True, help_text='Дополнительная пометка: ряд, коробка, секция', max_length=100)),
                ('condition', models.CharField(blank=True, help_text='Состояние экземпляра, например «как новая»', max_length=100)),
                ('acquired_from', models.CharField(blank=True, help_text='Где куплена или получена книга', max_length=120)),
                ('acquired_at', models.DateField(blank=True, help_text='Дата покупки или получения', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость экземпляра в выбранной валюте', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_gift', models.BooleanField(default=False, help_text='Получена ли книга в подарок')),
                ('notes', models.TextField(blank=True, help_text='Особые пометки: автограф, кому дать почитать и т.д.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelf_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_entry', to='shelves.shelfitem')),
            ],
            options={
                'ordering': ['-shelf_item__added_at', 'shelf_item__id'],
            },
        ),
    ]
