# Generated by Django 4.2.24 on 2025-10-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0011_homelibraryentry_enhancements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelibraryentry',
            name='acquired_from',
        ),
        migrations.RemoveField(
            model_name='homelibraryentry',
            name='is_gift',
        ),
        migrations.RemoveField(
            model_name='homelibraryentry',
            name='price',
        ),
    ]
