# Generated by Django 4.2.13 on 2026-02-18 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_bookeditrequest'),
        ('shelves', '0017_shelf_is_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfitem',
            name='selected_edition',
            field=models.ForeignKey(blank=True, help_text='Издание книги, которое пользователь выбрал при добавлении на полку.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_items', to='books.isbnmodel'),
        ),
    ]
