# Generated by Django 4.2.13 on 2026-03-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0019_bookprogressreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprogress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
