# Generated by Django 4.2.13 on 2026-03-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0020_alter_bookprogress_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookprogress',
            name='uniq_progress_no_event',
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='finished_at',
            field=models.DateField(blank=True, help_text='Дата завершения текущего цикла чтения', null=True),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активный трекер для текущего цикла чтения книги'),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='started_at',
            field=models.DateField(blank=True, help_text='Дата старта текущего цикла чтения', null=True),
        ),
        migrations.AddConstraint(
            model_name='bookprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', True), ('is_active', True)), fields=('user', 'book'), name='uniq_active_progress_no_event'),
        ),
    ]
