# Generated by Django 4.2.13 on 2026-07-11 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_book_hidden_at_book_hidden_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelves', '0021_remove_bookprogress_uniq_progress_no_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_list_items', to='books.book')),
                ('purchase_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shelves.purchaselist')),
            ],
            options={
                'ordering': ['-added_at', '-id'],
                'indexes': [models.Index(fields=['purchase_list', '-added_at'], name='shelves_pur_purchas_1580b3_idx'), models.Index(fields=['book'], name='shelves_pur_book_id_4cc4e5_idx')],
                'unique_together': {('purchase_list', 'book')},
            },
        ),
        migrations.AddIndex(
            model_name='purchaselist',
            index=models.Index(fields=['user', 'title'], name='shelves_pur_user_id_c60859_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaselist',
            unique_together={('user', 'title')},
        ),
    ]
