from django.urls import path

from . import auth_views, views, vk_app_collaboration_views, vk_app_views, vk_views

app_name = "api"

urlpatterns = [
    path("auth/register/", auth_views.AuthRegisterView.as_view(), name="auth-register"),
    path("auth/login/", auth_views.AuthLoginView.as_view(), name="auth-login"),
    path("auth/me/", auth_views.AuthMeView.as_view(), name="auth-me"),
    path("auth/logout/", auth_views.AuthLogoutView.as_view(), name="auth-logout"),
    path("auth/signup/", views.MobileSignupView.as_view(), name="auth-signup-legacy"),
    path("health/", views.HealthView.as_view(), name="health"),
    path("health", views.HealthView.as_view()),
    path("feature-map/", views.FeatureMapView.as_view(), name="feature-map"),
    path("feature-map", views.FeatureMapView.as_view()),
    path(
        "community/creation-payment/",
        views.CommunityCreationPaymentView.as_view(),
        name="community-creation-payment",
    ),
    path("community/creation-payment", views.CommunityCreationPaymentView.as_view()),
    path(
        "tracker/<int:progress_id>/story-payment/",
        views.TrackerStoryPaymentView.as_view(),
        name="tracker-story-payment",
    ),
    path(
        "tracker/<int:progress_id>/story-payment",
        views.TrackerStoryPaymentView.as_view(),
    ),
    path(
        "vk-app/tracker/<int:progress_id>/story-payment/",
        views.TrackerStoryPaymentView.as_view(),
        name="vk-app-tracker-story-payment",
    ),
    path(
        "vk-app/tracker/<int:progress_id>/story-payment",
        views.TrackerStoryPaymentView.as_view(),
    ),
    path("home/", views.HomeFeedView.as_view(), name="home"),
    path("home", views.HomeFeedView.as_view()),
    path("vk-app/home/", views.HomeFeedView.as_view(), name="vk-app-home"),
    path("vk-app/home", views.HomeFeedView.as_view()),
    path(
        "current-reading/image-payment/",
        views.CurrentReadingImagePaymentView.as_view(),
        name="current-reading-image-payment",
    ),
    path("current-reading/image-payment", views.CurrentReadingImagePaymentView.as_view()),
    path(
        "vk-app/current-reading/image-payment/",
        views.CurrentReadingImagePaymentView.as_view(),
        name="vk-app-current-reading-image-payment",
    ),
    path(
        "vk-app/current-reading/image-payment",
        views.CurrentReadingImagePaymentView.as_view(),
    ),
    path(
        "games/<slug:slug>/read-report-payment/",
        views.AnnualGameReportPaymentView.as_view(),
        name="annual-game-report-payment",
    ),
    path(
        "vk-app/games/<slug:slug>/read-report-payment/",
        views.AnnualGameReportPaymentView.as_view(),
        name="vk-app-annual-game-report-payment",
    ),
    path("random-book/", views.RandomShelfBookView.as_view(), name="random-book"),
    path("random-book", views.RandomShelfBookView.as_view()),
    path(
        "vk-app/random-book/",
        views.RandomShelfBookView.as_view(),
        name="vk-app-random-book",
    ),
    path("vk-app/random-book", views.RandomShelfBookView.as_view()),
    path("stats/", views.StatsView.as_view(), name="stats"),
    path("stats", views.StatsView.as_view()),
    path("books/", views.BookListView.as_view(), name="books-list"),
    path("books", views.BookListView.as_view()),
    path("books/<int:pk>/", views.BookDetailView.as_view(), name="books-detail"),
    path("books/<int:pk>", views.BookDetailView.as_view()),
    path("reading-clubs/", views.ReadingClubListView.as_view(), name="reading-clubs"),
    path("reading-clubs", views.ReadingClubListView.as_view()),
    path("reading-clubs/<slug:slug>/join/", views.ReadingClubJoinView.as_view(), name="reading-clubs-join"),
    path("reading-clubs/<slug:slug>/join", views.ReadingClubJoinView.as_view()),
    path("reading-clubs/<slug:slug>/", views.ReadingClubDetailView.as_view(), name="reading-clubs-detail"),
    path("reading-clubs/<slug:slug>", views.ReadingClubDetailView.as_view()),
    path("reading-clubs/<slug:slug>/topics/", views.ReadingClubTopicCreateView.as_view(), name="reading-clubs-topic-create"),
    path("reading-clubs/<slug:slug>/topics", views.ReadingClubTopicCreateView.as_view()),
    path("reading-clubs/<slug:slug>/topics/<int:pk>/", views.ReadingClubTopicDetailView.as_view(), name="reading-clubs-topic-detail"),
    path("reading-clubs/<slug:slug>/topics/<int:pk>", views.ReadingClubTopicDetailView.as_view()),
    path("reading-clubs/<slug:slug>/topics/<int:pk>/posts/<int:post_pk>/report/", views.DiscussionPostReportView.as_view(), name="reading-clubs-post-report"),
    path("reading-clubs/<slug:slug>/topics/<int:pk>/posts/<int:post_pk>/report", views.DiscussionPostReportView.as_view()),
    path("marathons/", views.ReadingMarathonListView.as_view(), name="marathons"),
    path("marathons", views.ReadingMarathonListView.as_view()),
    path("marathons/<slug:slug>/join/", views.ReadingMarathonJoinView.as_view(), name="marathons-join"),
    path("marathons/<slug:slug>/join", views.ReadingMarathonJoinView.as_view()),
    path("marathons/<slug:slug>/participants/<int:pk>/approve/", views.ReadingMarathonParticipantApproveView.as_view(), name="marathons-participant-approve"),
    path("marathons/<slug:slug>/participants/<int:pk>/approve", views.ReadingMarathonParticipantApproveView.as_view()),
    path("marathons/<slug:slug>/entries/<int:pk>/", views.ReadingMarathonEntryUpdateView.as_view(), name="marathons-entry-update"),
    path("marathons/<slug:slug>/entries/<int:pk>", views.ReadingMarathonEntryUpdateView.as_view()),
    path("marathons/<slug:slug>/entries/", views.ReadingMarathonEntryCreateView.as_view(), name="marathons-entry-create"),
    path("marathons/<slug:slug>/entries", views.ReadingMarathonEntryCreateView.as_view()),
    path("marathons/<slug:slug>/", views.ReadingMarathonDetailView.as_view(), name="marathons-detail"),
    path("marathons/<slug:slug>", views.ReadingMarathonDetailView.as_view()),
    path("vk/login/", vk_views.VKLoginView.as_view(), name="vk-login"),
    path("vk/connect/", vk_views.VKConnectView.as_view(), name="vk-connect"),
    path("vk/me/", vk_views.VKMeView.as_view(), name="vk-me"),
    path("vk/shelf/", vk_views.VKShelfView.as_view(), name="vk-shelf"),
    path("vk/progress-feed/", vk_views.VKProgressFeedView.as_view(), name="vk-progress-feed"),
    path("vk/progress-feed/<int:progress_id>/reaction/", vk_views.VKProgressReactionView.as_view(), name="vk-progress-feed-reaction"),
    path("vk/public-shelf/<int:vk_user_id>/", vk_views.VKPublicShelfView.as_view(), name="vk-public-shelf"),
    path("vk/widget/<int:vk_user_id>/", vk_views.VKWidgetView.as_view(), name="vk-widget"),
    path("vk-app/auth/login/", vk_app_views.VKAppLoginView.as_view(), name="vk-app-login"),
    path("vk-app/auth/register/", vk_app_views.VKAppRegisterView.as_view(), name="vk-app-register"),
    path("vk-app/image-proxy/", vk_app_views.VKAppImageProxyView.as_view(), name="vk-app-image-proxy"),
    path("vk-app/generated-images/", vk_app_views.VKAppGeneratedImageUploadView.as_view(), name="vk-app-generated-images"),
    path("vk-app/notifications/", vk_app_views.VKAppNotificationsView.as_view(), name="vk-app-notifications"),
    path("vk-app/collaborations/", vk_app_collaboration_views.VKAppCooperationOverviewView.as_view(), name="vk-app-collaborations"),
    path("vk-app/collaborations/offers/", vk_app_collaboration_views.VKAppCooperationOfferCreateView.as_view(), name="vk-app-collaboration-offers"),
    path("vk-app/collaborations/blogger-requests/", vk_app_collaboration_views.VKAppCooperationBloggerRequestCreateView.as_view(), name="vk-app-collaboration-blogger-requests"),
    path("vk-app/collaborations/offers/<int:pk>/respond/", vk_app_collaboration_views.VKAppCooperationOfferRespondView.as_view(), name="vk-app-collaboration-offer-respond"),
    path("vk-app/collaborations/blogger-requests/<int:pk>/respond/", vk_app_collaboration_views.VKAppCooperationBloggerRequestRespondView.as_view(), name="vk-app-collaboration-blogger-request-respond"),
    path("vk-app/collaborations/responses/<str:kind>/<int:pk>/accept/", vk_app_collaboration_views.VKAppCooperationResponseAcceptView.as_view(), name="vk-app-collaboration-response-accept"),
    path("vk-app/collaborations/responses/<str:kind>/<int:pk>/decline/", vk_app_collaboration_views.VKAppCooperationResponseDeclineView.as_view(), name="vk-app-collaboration-response-decline"),
    path("vk-app/collaborations/responses/<str:kind>/<int:pk>/withdraw/", vk_app_collaboration_views.VKAppCooperationResponseWithdrawView.as_view(), name="vk-app-collaboration-response-withdraw"),
    path("vk-app/collaborations/responses/<str:kind>/<int:pk>/comments/", vk_app_collaboration_views.VKAppCooperationResponseCommentView.as_view(), name="vk-app-collaboration-response-comments"),
    path("vk-app/collaborations/<int:pk>/approve/", vk_app_collaboration_views.VKAppCooperationApproveView.as_view(), name="vk-app-collaboration-approve"),
    path("vk-app/collaborations/<int:pk>/status/", vk_app_collaboration_views.VKAppCooperationStatusView.as_view(), name="vk-app-collaboration-status"),
    path("vk-app/collaborations/<int:pk>/review-links/", vk_app_collaboration_views.VKAppCooperationReviewLinksView.as_view(), name="vk-app-collaboration-review-links"),
    path("vk-app/collaborations/<int:pk>/messages/", vk_app_collaboration_views.VKAppCooperationMessageView.as_view(), name="vk-app-collaboration-messages"),
    path("vk-app/games/", vk_app_views.VKAppGamesView.as_view(), name="vk-app-games"),
    path("vk-app/games/<slug:slug>/", vk_app_views.VKAppGameDetailView.as_view(), name="vk-app-games-detail"),
    path("vk-app/reward-ads/start/", vk_app_views.VKAppRewardAdStartView.as_view(), name="vk-app-reward-ads-start"),
    path("vk-app/reward-ads/claim/", vk_app_views.VKAppRewardAdClaimView.as_view(), name="vk-app-reward-ads-claim"),
    path("vk-app/profile/", vk_app_views.VKAppProfileView.as_view(), name="vk-app-profile"),
    path(
        "vk-app/profiles/<str:username>/",
        vk_app_views.VKAppPublicProfileView.as_view(),
        name="vk-app-public-profile",
    ),
    path("vk-app/statistics/", vk_app_views.VKAppStatisticsView.as_view(), name="vk-app-statistics"),
    path("vk-app/reviews/", vk_app_views.VKAppReviewListView.as_view(), name="vk-app-reviews"),
    path(
        "reviews/<int:rating_id>/image-payment/",
        views.ReviewImagePaymentView.as_view(),
        name="review-image-payment",
    ),
    path(
        "vk-app/reviews/<int:rating_id>/image-payment/",
        views.ReviewImagePaymentView.as_view(),
        name="vk-app-review-image-payment",
    ),
    path("vk-app/genres/", vk_app_views.VKAppGenreListView.as_view(), name="vk-app-genres"),
    path("vk-app/books/", vk_app_views.VKAppBookListCreateView.as_view(), name="vk-app-books-list"),
    path("vk-app/books/discovery/", vk_app_views.VKAppBookDiscoveryView.as_view(), name="vk-app-books-discovery"),
    path("vk-app/books/external-search/", vk_app_views.VKAppBookExternalSearchView.as_view(), name="vk-app-books-external-search"),
    path("vk-app/purchase-lists/", vk_app_views.VKAppPurchaseListView.as_view(), name="vk-app-purchase-lists"),
    path("vk-app/purchase-lists/<int:list_id>/", vk_app_views.VKAppPurchaseListDetailView.as_view(), name="vk-app-purchase-lists-detail"),
    path("vk-app/purchase-lists/<int:list_id>/items/", vk_app_views.VKAppPurchaseListItemView.as_view(), name="vk-app-purchase-lists-items"),
    path("vk-app/books/<int:pk>/", vk_app_views.VKAppBookDetailView.as_view(), name="vk-app-books-detail"),
    path("vk-app/books/<int:pk>/reviews/", vk_app_views.VKAppBookReviewListCreateView.as_view(), name="vk-app-books-reviews"),
    path("vk-app/books/<int:pk>/shelf/", vk_app_views.VKAppBookShelfView.as_view(), name="vk-app-books-shelf"),
    path("vk-app/books/<int:pk>/tracker/", vk_app_views.VKAppBookTrackerView.as_view(), name="vk-app-books-tracker"),
    path("vk-app/tracker/<int:progress_id>/", vk_app_views.VKAppBookTrackerView.as_view(), name="vk-app-tracker"),
]


# Keep the rest of the site available during a rolling deployment where
# urls.py may reach the server a moment before the matching view module.
if hasattr(views, "MonthlySummaryPaymentView"):
    urlpatterns += [
        path(
            "statistics/monthly-summary-payment/",
            views.MonthlySummaryPaymentView.as_view(),
            name="monthly-summary-payment",
        ),
        path(
            "statistics/monthly-summary-payment",
            views.MonthlySummaryPaymentView.as_view(),
        ),
        path(
            "vk-app/statistics/monthly-summary-payment/",
            views.MonthlySummaryPaymentView.as_view(),
            name="vk-app-monthly-summary-payment",
        ),
        path(
            "vk-app/statistics/monthly-summary-payment",
            views.MonthlySummaryPaymentView.as_view(),
        ),
    ]
